nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  etisoftware:
    npmRegistryServer: "https://docker.etisoftware.com:443/artifactory/api/npm/npm-local/"
    npmAlwaysAuth: true
    npmAuthToken: ""

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
